sudo: required
language: ruby
rvm:
- 2.3.1
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6
  global:
  - WORKDIR=/source
  - VERSION=2.11.0
  - secure: hPKAgN16LTn0Tspn8j3d5RCReEATZP6naM/T8HP8UaVeMuEjjzF6LSOTYlhHT5UOoklC91YHHf45kWoCCkgXCGLzGoTE0hI4NVZzDPOLtmD6UQQxp/uCtYV3mgJcSZSYQvEsPsrbiMTvdVAz++M8k8BQLfj0MRi2L9iMUUDsfAVB9PXzDx2olAie8uPH3dvg5ji+yjKeSCdvpeFdAO76RoAlMuPdy/u5hI8I/H4nFSYkV0m+JGtXn6tnQ+0h+DwrBQkdt+8H/3WsffYe97FuaVHfu0WYVH3qobHGOVYdn052YzdrSRqJYCoh4M81RJfKH4nGu7ElisedhAN2dbtkj1fP6uPDHBXPsHLqwV9ywuWmCbSmtTStuA0H4lQXu5DAMT9JfyKmfMHRrt7Nwo1jq8SLhBTNqw0IO5ulkIpC3FPOfKVQNQZ+sbvGFKMZe1xWsre3neFpnvcwQMaGfU6D2xaWcQmq6zGaI6HjHPdfl6KwqYOuezS8BoEJcthCqS8A1ckvHuKtPXuOaK7NiHNMCGPUpISuxZKo4MZ5mSrFgZLxVvCfAmw0PgaOHNrgL/F8pIDr0iFXZS9CB+ASjAlpxX66ps/ouCypvrX7wNAl9eb4y1s30XyS5d7Gb7IstS8L7wMKGLRxIOc5Zej16Z/N57RCrCdRQ2v+JoPzweuWZaw=
services:
- docker
before_install:
- echo $password | gpg --passphrase-fd 0 rpm-signing.tar.asc
- tar xf rpm-signing.tar
- mkdir -p $(pwd)/.gnupg && chmod 700 $(pwd)/.gnupg
- gpg --no-default-keyring --secret-keyring .gnupg/secring.gpg --keyring .gnupg/pubring.gpg
  --import rpm-signing.asc
install:
- docker build -t rpm-git .
before_script:
- mkdir -p $(pwd)/rpmbuild/SOURCES
- curl -# -L -o $(pwd)/rpmbuild/SOURCES/git-${VERSION}.tar.gz http://kernel.org/pub/software/scm/git/git-${VERSION}.tar.gz
script:
- test "${TRAVIS_BRANCH}" = "master" && RELEASE_VERSION="`date +%Y%m%d%H%M`.`git rev-parse --short ${TRAVIS_BRANCH}`" || RELEASE_VERSION=""
- docker run --rm=true -v $(pwd):${WORKDIR}:rw -E "RELEASE_VERSION=${RELEASE_VERSION}" --env-file $(pwd)/.env rpm-git bash ${WORKDIR}/build.sh
- docker run --rm=true -v $(pwd):${WORKDIR}:rw centos:${OS_TYPE}${OS_VERSION} bash
  -c "find /source -name \"*.rpm\" -type f | xargs -I{} yum -y localinstall {}"
