sudo: required
language: ruby
rvm:
  - 2.3.1
env:
  matrix:
    - OS_TYPE=centos OS_VERSION=6
  global:
    - WORKDIR=/source
    - VERSION=2.11.0
services:
  - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_2161859b8f88_key -iv $encrypted_2161859b8f88_iv -in rpm-signing.asc.enc -out rpm-signing.asc -d
install:
  - docker build -t rpm-git .
before_script:
  - mkdir -p $(pwd)/rpmbuild/SOURCES
  - curl -# -L -o $(pwd)/rpmbuild/SOURCES/git-${VERSION}.tar.gz http://kernel.org/pub/software/scm/git/git-${VERSION}.tar.gz
script:
  - docker run --rm=true -v $(pwd):${WORKDIR}:rw rpm-git bash -e -v "${WORKDIR}/build.sh"
  - docker run --rm=true -v $(pwd):${WORKDIR}:rw centos:${OS_TYPE}${OS_VERSION} bash -c "find /source -name \"*.rpm\" -type f | xargs -I{} yum -y localinstall {}"
