sudo: required
language: ruby
rvm:
    - 2.3.1
env:
    matrix:
        - OS_TYPE=centos OS_VERSION=6
    global:
        - BASE_DIR=/code
services:
    - docker
before_install:
    - sudo docker pull centos:centos${OS_VERSION}
script:
    - sudo docker run --rm=true -v `pwd`:${BASE_DIR}:rw centos:centos${OS_VERSION} /bin/bash -e -v ${BASE_DIR}/build.sh

