sudo: required
env:
    matrix:
        - OS_TYPE=centos OS_VERSION=6
services:
  - docker
before_install:
    - sudo docker pull centos:centos${OS_VERSION}
script:
    - sudo docker run --rm=true -v `pwd`:/code:rw centos:centos6 /bin/cat /etc/redhat-release

