sudo: required
language: ruby
rvm:
- 2.3.1
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6
  global:
  - WORKDIR=/source
  - secure: hPKAgN16LTn0Tspn8j3d5RCReEATZP6naM/T8HP8UaVeMuEjjzF6LSOTYlhHT5UOoklC91YHHf45kWoCCkgXCGLzGoTE0hI4NVZzDPOLtmD6UQQxp/uCtYV3mgJcSZSYQvEsPsrbiMTvdVAz++M8k8BQLfj0MRi2L9iMUUDsfAVB9PXzDx2olAie8uPH3dvg5ji+yjKeSCdvpeFdAO76RoAlMuPdy/u5hI8I/H4nFSYkV0m+JGtXn6tnQ+0h+DwrBQkdt+8H/3WsffYe97FuaVHfu0WYVH3qobHGOVYdn052YzdrSRqJYCoh4M81RJfKH4nGu7ElisedhAN2dbtkj1fP6uPDHBXPsHLqwV9ywuWmCbSmtTStuA0H4lQXu5DAMT9JfyKmfMHRrt7Nwo1jq8SLhBTNqw0IO5ulkIpC3FPOfKVQNQZ+sbvGFKMZe1xWsre3neFpnvcwQMaGfU6D2xaWcQmq6zGaI6HjHPdfl6KwqYOuezS8BoEJcthCqS8A1ckvHuKtPXuOaK7NiHNMCGPUpISuxZKo4MZ5mSrFgZLxVvCfAmw0PgaOHNrgL/F8pIDr0iFXZS9CB+ASjAlpxX66ps/ouCypvrX7wNAl9eb4y1s30XyS5d7Gb7IstS8L7wMKGLRxIOc5Zej16Z/N57RCrCdRQ2v+JoPzweuWZaw=
services:
- docker
before_install:
- echo $password | gpg --passphrase-fd 0 rpm-signing.tar.asc
- tar xf rpm-signing.tar
- mkdir -p $(pwd)/.gnupg && chmod 700 $(pwd)/.gnupg
- gpg --no-default-keyring --secret-keyring .gnupg/secring.gpg --keyring .gnupg/pubring.gpg
  --import rpm-signing.asc
install:
- docker build -t rpm-git .
script:
- VERSION=$(echo ${TRAVIS_TAG} | cut -d_ -f1)
- RELEASE=$(echo ${TRAVIS_TAG} | cut -d_ -f2)
- docker run --rm=true -v $(pwd):${WORKDIR}:rw --env-file $(pwd)/.env rpm-git 
  ${WORKDIR}/build.sh ${VERSION} ${RELEASE}
- docker run --rm=true -v $(pwd):${WORKDIR}:rw centos:${OS_TYPE}${OS_VERSION} bash
  -c "find /source -name \"*.rpm\" -type f | xargs -I{} yum -y localinstall {}"
deploy:
  provider: packagecloud
  repository: centos
  username: laksmana
  token:
    secure: U3El5NLT4nLLFsu5kHymZyTLQubd+Wa3ClVbRfVJBRbnaNeARsEr7AwLMikEimvh9Sbrptdz52SWXQ7Ov0hOXczas3SpV7TjRolsQ8sLQfhIPK833zm5ea8QeznH2xZt24AkOJxK17LVRZ9E4tvQcDdRWg28AZSuiful+nB02MCt6GObtdt1pXvsFgW/NIdslbyLLJqALPMnSRByXQN1hx3n9hYa3F3BYqVjuHuzzMDGuD94cop7FucKAOWhlQdUHLfKSfNIfE4h5Uu88nHFdPizfiZXhdER2AAl2JwurneTEWynbg5EHADtBRvkeRGm/5eW/S6/c6sGqTr9CTvIwPgPsL8WIGRanVvZA1kOltODUILF/KlSe39u0pKFAwXtPIaIr2ryuOlPXRtw9JiZjSlSICXiIGYAU43Ye8tl71CaaOwt8Vk0XGd9JGrEt5poiwk1IyK37vJ6em/W1/7PO5D5Eaw+jpZBbqsO05z2bGGOYmUjOpxd5khuMFv5LiSYR5QAPsFuWfXicdCbPimjfflPphzVuYHoiq4pdckTEekrM/LpkpBVE+rM4bLJ0SAHmv2M5MvLKTPQQUWE0FTpl/tOQkslav91F4k8b/WODw1jNpa0AhzXziOLXxCzWcxgqx8oLybpcZ5JyTeaxFRglIwtuSVSAATugRFZ+U2uuSc=
  dist: el/6
  package_glob: rpmbuild/RPMS/x86_64/*.rpm
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    rooms:
      secure: tE5qYhFdimeF6Ybec+ve0IMfStYiouoSwFa8aV305rrCgMy+/ugyx5A1Sp4q71V1tBJhz7a8/HTHXlhshCSsQ6DJUdZPSSofsniqnbpZGgR7Ycsk7gQrqyAo5KqxlHFOmh/nyqx7RME9gcxpXV7Q1pHbWbue/Y3NG3JzZdGp2+4RueRLRJgMoThVaqiytYeAq6u02TtfXSz2uIS3yqkrtjDeKKPzYYJznVnkHRatOoWrIg5+LelrTZttOfqZVZQl7w0ZlzlEyro10NfhwEYMcGte5dVtPYZyDzGOmdq1fAJkNjsvp0As6sbYAwQgX1BmFvPTX6UTeOnMpVs9HqrECjU9CZlSK9eYq2JNSUxzBuJ8ZJ0ZUdASTUmtPYm+PYMKakGVFl6Ia9c78xk/31pNUflyUji1hxi/jbLqlupzEC3T/JrurwZEiE5uxCeqUOafiy6CVaLGjI8Hv7rSysAGHvq2Nhl30JSqeM8m2mVSeSkRuBehbrRMcYn+LXqtQzVrBdouCMfPOCVpRmY6qoR66c+6DdouxrH73c0Pv6vLoykIY7PUhVFRcPshp6ZRNhI2O/6mrG8Dbcz150Om/byQ6ZpyNMwqKvB8vZ2lGX2XmHc00UkLW8wiDK24+9cDkW+l1givaHdKi+Eu4Jz6/KeG2SHCgJimDiKAZnORHEzfbJs=
